### ISSUE TITLE
SSL errors when connecting to libsdl.org

### ISSUE THREAD

**Issue by Jark5455** [libsdl-org/sdlweb#20]
Hello,

I get some certificate verification errors when trying to connect to libsdl.org

```
$ openssl s_client -connect www.libsdl.org:443
Connecting to 2604:a880:1:20::181:e001
CONNECTED(00000003)
depth=0 CN=libsdl.org
verify error:num=20:unable to get local issuer certificate
verify return:1
depth=0 CN=libsdl.org
verify error:num=21:unable to verify the first certificate
verify return:1
depth=0 CN=libsdl.org
verify return:1
```

SSL Labs also shows that there are some missing certificates

![Screenshot_2024-06-08_19-27-39](https://github.com/libsdl-org/sdlweb/assets/39651378/0d2823e7-3e98-4e21-bbe2-8edef7dd7176)

**Comment by icculus** [comment]
So I was wondering why our GitHub webhooks started failing on June 6th, and sure enough, Let's Encrypt's root certificates changed on that day:

https://letsencrypt.org/certificates/

First line of that page:

> Note: This section describes Let’s Encrypt’s hierarchy as of June 6, 2024. For the hierarchy in use prior to June 6, [see below](https://letsencrypt.org/certificates/#old-content).

I'm going to figure out how to update the certs, which should resolve it.

**Comment by icculus** [comment]
Yeah, certbot updated the intermediate certs, but put them in a new directory (libsdl.org-0001 instead of libsdl.org), so Apache was serving the latest SSL certificate with the wrong intermediate certs.

I took out the (incorrect!) custom Apache config line that caused this, so now it uses certbot's config whenever it updates it. I also turned off TLSv1 and v1.1 support and we're good to go!

![image](https://github.com/libsdl-org/sdlweb/assets/673562/f071f806-fdf2-4ff1-8cdb-a8ab4f10b4a6)
